### ISSUE TITLE
Add support for murmur3 hash function.

### ISSUE THREAD

**Issue by kadishmal** [liushoukai/node-hash-functions#3]
There are other npm modules that provide murmur3 hash function however it would be nice to have all in one module like `node-hashes`.

This seems to be in active development https://github.com/hideo55/node-murmurhash3.

**Comment by liushoukai** [comment]
Yah, Can we put it together? :)

**Comment by kadishmal** [comment]
All right! I will see what I can do. Thanks!

**Comment by liushoukai** [comment]
Already supported for the MurmurHash3
